os:
  - linux
  - osx
language: perl6
perl6:
  - latest
install:
  - rakudobrew build moar 2018.10
  - rakudobrew switch moar-2018.10
  - rakudobrew build zef
  - zef install Test::META
  - zef install --deps-only --/test .
script:
  - zef test .
sudo: false
